name: github pages

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'

jobs:
  skipcd:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "[Skip CD] ${{ contains(github.event.head_commit.message, '[skip cd]') }}"
      - run: echo "[Skip CD] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  deploy:
    runs-on: ubuntu-18.04
    if: |
      contains(github.event.head_commit.message, '[skip cd]') == false &&
      contains(github.event.head_commit.message, '[skip ci]') == false
    steps:

    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
      id: nvm

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci

    - run: npm test

    - run: npm run generate

    - name: Deploy (script mode)
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
        SCRIPT_MODE: true
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        bash ./entrypoint.sh
